'use client';
import { MouseEventHandler, useState } from 'react'
import RandomFox from "@/componentes/RandomFox";
import Head from "next/head";

//tipado del useState -> es el tipado de c/elemnt del array
type ImageItem = {id: number, url: string};

//funcion para elegir de forma random un num de 1 al 123 para las img de la pagina
const random  = () => Math.floor(Math.random() * 123) + 1;


export default function Home() {

  //estado para varias imagenes
  //tipado para el estado --> lo creo arriba
  const [images, setImages] = useState<Array<ImageItem>>([ 
    { id: 1, url: `https://randomfox.ca/images/${random()}.jpg` },
  ]);

  //funcion para agregar una img al hacer clcik
  //el tipado lo descubro poniendo el mouse sobre el evento onClick del boton
  const handleOnClick: MouseEventHandler<HTMLButtonElement> = (e) => {
    const newId = images.length + 1;
    setImages([
      ...images,
      { id: newId, url: `https://randomfox.ca/images/${random()}.jpg` },
    ]);
  };

  //creo url para la api
  //const image: string = `https://randomfox.ca/images/${random()}.jpg`;


  return (
    <div>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <h1 className="text-3xl font-bold ">Curso-Platzi React con TypeScript 👀</h1>
        <button onClick={(e) => handleOnClick(e)}>Agregar imagenes</button>
        {
          images.map((image, index) => (
            <div className="p-4" key={index}>
              <RandomFox image={image.url} alt="Not Found"/>
            </div>
        ))}
      </main>
      
      <footer>

      </footer>
    </div>
    
  );
}
